# Copyright (c) 2013 - 2016 blacktop Joshua Maine, All Rights Reserved.
# See LICENSE for license information.

#######################################################################
# MALICE Configuration ################################################
#######################################################################

title = "Malice Runtime Configuration"

[author]
  name = "blacktop"
  organization = "The Blacktop Company"

[web]
  url = "0.0.0.0:80"
  api = ":3993"
  admin_url = "127.0.0.1:3333"

[email]
  host = "smtp.example.com"
  port = 25
  user = "username"
  pass = "password"

[database]
  name = "malice-elk"
  image = "blacktop/elk"
  server = "localhost" # This is for running on Docker for Mac installations.
  ports = [ 9200 ]
  timeout = 10
  enabled = true

[environment]
  run = "development"
  # run = "production"

[docker]
  machine-name = "malice"
  endpoint = "tcp://localhost:2376"
  binds = "malice:/malware:ro"
  links = "malice-elk:elastic"
  timeout = 120

[logger]
  filename = "malice.log"
  maxsize = 10
  maxage = 30
  maxbackups = 7
  localtime = false

[proxy]
  enable = false
  http = ""
  https = ""
